adminapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    # path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    # path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<pk>/', adminapp.products, name='products'),
    path('products/read/category/<pk>/', adminapp.ProductListView.as_view(), name='products'),
    # path('products/read/<pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    # path('products/update/<pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('delete/<int:pk>/', basketapp.delete, name='delete'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category<int:pk>/', mainapp.products, name='category'),
    path('category<int:pk>/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),

]

ordersapp/urls.py
from django.urls import path, include
from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderDetailView.as_view(), name='order_read'),
    path('edit/<int:pk>/', ordersapp.OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDeleteView.as_view(), name='order_delete'),
    path('complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='product_images', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=100, verbose_name='краткое описание', blank=True)
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество на складе')
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import json

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory

links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]


# def get_basket(user):
#     if user.is_authenticated:
#         return Basket.objects.filter(user=user)
#     return []


def get_hot_product():
    products_list = Product.objects.all()
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    return Product.objects.filter(category__pk=hot_product.category.pk).exclude(pk=hot_product.pk)[:3]


def main(request):
    products = Product.objects.all()[:4]
    context = {
        'title': 'Главная',
        'products': products,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category = {'name': 'все', 'pk': 0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        paginator = Paginator(products_list, 2)
        try:
            product_paginator = paginator.page(page)
        except PageNotAnInteger:
            product_paginator = paginator.page(1)
        except EmptyPage:
            product_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'products': product_paginator,
            'category': category,
        }

        return render(request, 'mainapp/products_list.html', context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'title': 'Продукты',
        'links_menu': links_menu,
        'same_products': same_products,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'продукты'
    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
    }
    return render(request, 'mainapp/product.html', context)


def contacts(request):
    json_data = json.loads(open('mainapp/contacts_data.json').read())
    context = {
        'title': 'Контакты',
        'phone': 'Телефон',
        'email': 'Email',
        'address': 'Адрес',
        'contacts': json_data,
    }

    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
        <li>
            <a href="{% url 'products:category' 0 %}">
                все
            </a>
        </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}" {% if request.resolver_match.kwargs.pk == link.pk %}class="active"{% endif %}>
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_location_menu.html
<div class="location">
    {% for contact in contacts %}
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>{{ contact.city }}</h4>
            <div class="contacts">
                <h5>{{ phone }}</h5>
                <p>{{ contact.phone }}</p>
            </div>
            <div class="contacts">
                <h5>{{ email }}</h5>
                <p>{{ contact.e_mail }}</p>
            </div>
            <div class="contacts">
                <h5>{{ address }}</h5>
                <p>{{ contact.address}}</p>
            </div>
        </div>
    {% endfor %}
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
<ul class="menu">
    <li><a href="{% url 'main' %}" {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>домой</a></li>
    <li><a href="{% url 'products:index' %}" {% if request.resolver_match.namespace == 'products' %}class="active"{% endif %}>продукты</a></li>
    <li><a href="{% url 'contacts' %}" {% if request.resolver_match.url_name == 'contacts' %}class="active"{% endif %}>контакты</a></li>
    {% if user.is_authenticated %}
        <li>
           <div class="dropdown">
               <a class="dropdown-toggle" href="" data-toggle="dropdown">
                   {{ user.first_name|default:'Пользователь' }}
                   <span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                   <li>
                       <a href="{% url 'auth:edit' %}">
                           профиль
                       </a>
                   </li>
                   <li>
                       <a href="{% url 'ordersapp:orders_list' %}">
                           заказы
                       </a>
                   </li>
               </ul>
           </div>
       </li>
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:users' %}">админка</a>
            </li>
            {% endif %}
        <li><a href="{% url 'auth:logout' %}">выход</a></li>
    {% else %}
        <li><a href="{% url 'auth:login' %}">вход</a></li>
    {% endif %}
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %}{{ basket.0.total_cost|floatformat:0 }}руб. ({{ basket.0.total_quantity }} шт.){% endif %}
    </span>
</a>